name: kyle.j.miller
favicon: null
layout_spectrum: 0.22587
typography_spectrum: 0.9775337022729218
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.125
  lightness: 0.7124355018604547
  saturation: 0.9625439075753093
  rhythmicContrast: 0.37842922867275774
purpose: []
